### ISSUE TITLE
NPM package rename to 'ot-rich-text'?

### ISSUE THREAD

**Issue by pedrosanta** [ottypes/rich-text#10]
Noticed that the other type NPM package names follow `ot-*` (eg. `ot-text`), and `rich-text` seems like a very generic name given that it's mostly related to OT, no?

Should a package rename to `ot-rich-text` be considered?

**Comment by jhchen** [comment]
This package is a format for representing rich text and while it supports OT, that's not the only use case. For example [Quill](https://github.com/quilljs/quill) uses rich-text to represent its internal document and support its undo manager.

**Comment by pedrosanta** [comment]
Ok, gonna do a package rename on PR #12 then. :)
