### ISSUE TITLE
Uncaught Error: diff() called on non-document

### ISSUE THREAD

**Issue by freakycue** [ottypes/rich-text#13]
Hey,
I experience the issue with [Quill](https://github.com/quilljs/quill) on bookmarklet script. After running it on http://www.dwr.com/ initialisation of quill fails with `Uncaught Error: diff() called on non-document`. I found, that it happens, because `clone` method of the `op` returns string instead of object.
After replacing original clone method from https://github.com/ottypes/rich-text/blob/master/lib/op.js#L6,
with
```
clone: function (attributes, keepNull) {
      if (!is.object(attributes)) return {};
      var memo = {};
      Object.keys(attributes).forEach(function(key) {
        if (attributes[key] !== undefined && (attributes[key] !== null || keepNull)) {
          memo[key] = attributes[key];
        }
      });
      return memo;
    },
```
everything goes normal. I think it could happen, because original website using some polyfil script. Any thoughts, how to fix or avoid this would be appreciate.

**Comment by jhchen** [comment]
I don't see how a string could be returned by the current `clone` implementation. All code paths appear to lead to an object. Do you have a failing test to demonstrate this?

**Comment by freakycue** [comment]
Some script on http://www.dwr.com/ replace standard reduce to it's own implementation. The same thing happens on  http://lightolier.com. One of the ways to fix that is to use lodash, anyway quill has it as dependency.

**Comment by Predjo** [comment]
+1 I have also expirenced that problem.Any kind of fix would be great.

**Comment by freakycue** [comment]
@jhchen, when I'm trying to run `[1, 2, 3].reduce(function(memo, num) {return memo + num;}, 0);` on http://www.dwr.com/, I'm getting `[1, 2, 3, 4]` as result.

**Comment by jhchen** [comment]
https://github.com/ottypes/rich-text/blob/master/lib/op.js#L6 explicitly passes in `{}` as the initial value. It's not possible for the initial value to be zero...

**Comment by freakycue** [comment]
Fixed by replacing `Array.prototype.reduce` with right implementation.
