### ISSUE TITLE
Insert Embed Operation

### ISSUE THREAD

**Issue by sachinrekhi** [ottypes/rich-text#16]
Jason,

Under the Insert Operation section of the [README](https://github.com/ottypes/rich-text), you mention the following syntax for embeds:

```
// Insert an embed
{
  insert: { image: 'https://octodex.github.com/images/labtocat.png' },
  attributes: { alt: "Lab Octocat" }
}
```

However based on what I've read on [Deltas - Quill Documentation](http://quilljs.com/docs/deltas/) it looks like what QuillJS generates for embeds is this:

```
// Insert an image
{
  insert: 1,
  attributes: {
    image: 'https://octodex.github.com/images/labtocat.png'
  }
}
```

It looks like your rich-text ottype implementation supports both. Is it correct that we need to support the insert key value being a string (for text) and both a number or a dict for an embed? Are you planning on using both in Quill?

**Comment by jhchen** [comment]
Quill 1.0 will accept both as input but will output the former. Rich-text is agnostic to the format--it just accepts anything non-string as a length 1 unique insert.
