### ISSUE TITLE
Small documentation nit in Quick Example

### ISSUE THREAD

**Issue by sachinrekhi** [ottypes/rich-text#18]
Thought I'd point out a small documentation nit that might confuse some folks.

The **Quick Example** section shows the following:

```
delta.compose(death);
// delta is now:
// {
//   ops: [
//     { insert: 'Gandalf ', attributes: { bold: true } },
//     { insert: 'the ' },
//     { insert: 'White', attributes: { color: '#fff' } }
//   ]
// }
```

It suggests that the existing delta object has changed. But in fact the semantics of compose don't edit the delta itself, but simply return a new composed delta. A more accurate documentation to reflect this might be the following:

```
var composed = delta.compose(death);
// composed is:
// {
//   ops: [
//     { insert: 'Gandalf ', attributes: { bold: true } },
//     { insert: 'the ' },
//     { insert: 'White', attributes: { color: '#fff' } }
//   ]
// }
```

**Comment by jhchen** [comment]
Thanks for the pointer!
