### ISSUE TITLE
diff() not working as expected

### ISSUE THREAD

**Issue by klikstermkd** [ottypes/rich-text#19]
Here's the issue.

If there are two deltas:

```
var oldDelta = new Delta().insert('ab', {bold: true}).insert('cd');
var newDelta = new Delta().insert('abz', {bold: true}).insert('cd');
```

And the `diff` function is applied like so:

`var diffedDelta = oldDelta.diff(newDelta);`

Than `diffedDelta`'s operations will look like:

```
{
  ops: [
    {
      retain: 2
    },
    {
      attributes: {
        bold: true
      },
      insert: 'z'
    }
  ]
}
```

But, if `newDelta` is changed to:

`var newDelta = new Delta().insert('abc', {bold: true}).insert('cd');`

Notice that instead of inserting `abz` we insert `abc`.

Than `diffedDelta`'s operations will look like:

```
{
  ops: [
    {
      retain: 2
    },
    {
      retain: 1,
      attributes: {
        bold: true
      }
    },
    {
      insert: 'c'
    }
  ]
}
```

Which is not the same as before when we inserted `abz`. There is an extra operation.

In the first case the text is `abzcd` and in the second case it's `abccd`, so the issue is if the newly inserted character between `ab` and `cd` is the same as the first character from `cd` than it behaves differently. 

After digging through the code, I found that the issue is in the function `diff_commonPrefix` inside the `fast-diff` library, mainly in the binary search code.

**Comment by jhchen** [comment]
While perhaps peculiar the result is not wrong. The diff() still returns the delta that would get you from one document to another. Is this causing a bug in your use case or were you just surprised by the output?

**Comment by klikstermkd** [comment]
Yes it is causing a bug. I use the library in a rich text editor, and it causes the editor to misbehave. Any clues on how to overcome it?

**Comment by jhchen** [comment]
Can you provide more details about the use case?

**Comment by klikstermkd** [comment]
For instance, if the text in the editor is as follows: "**ab**cd"
And I insert a character "c" between "b" and "c" it will become "**abcc**d".

The first "c" is the one we inserted and it's bold because it took the formatting from "ab". But as you can see, the second "c" from "cd" also became bold because of the extra operation created from diffing the deltas. So the operations after diffing look like:

```
{
  ops: [
    {
      retain: 2
    },
    {
      retain: 1,
      attributes: {
        bold: true
      }
    },
    {
      insert: 'c',
      attributes: {
        bold: true
      }
    }
  ]
}
```

**Comment by jhchen** [comment]
So you start with **ab**cd and apply the delta (which was returned by a `diff()`):

```js
{
  ops: [
    {
      retain: 2
    },
    {
      retain: 1,
      attributes: {
        bold: true
      }
    },
    {
      insert: 'c'
    }
  ]
}
```

The diff() instructions say insert a 'c', not a bolded 'c'. So if the editor respected the instructions it is given, it would correctly result in *abc*cd. I've tried this scenario on Quill and it behaves correctly. Also you should try the following scenario on your editor which shows why the editor needs to not be too helpful in adding formats you did not instruct:

1. User A and B sees the document **abc**
2. User A puts his cursor after the "c", unbolds the text and types 'd'
3. User A now sees **abc**d

The diff() between **abc** and **abc**d is unambiguously [{ retain: 3 }, { insert: 'd' }]. If you had an editor that was too helpful in formatting for you, you could not get user B to see **abc**d.

**Comment by klikstermkd** [comment]
If we apply the delta on **ab**cd the diff will return:

```
{
  ops: [
    {
      retain: 2
    },
    {
      retain: 1,
      attributes: {
        bold: true
      }
    },
    {
      insert: 'c',
      attributes: {
        bold: true
      }
    }
  ]
}
```

**Comment by klikstermkd** [comment]
I dig through Quill's code, and inside the `_trackDelta` function there is code that works for me, i.e. the code for diffing only the left deltas.
