### ISSUE TITLE
compose with { retain: 0 } does not work correctly

### ISSUE THREAD

**Issue by mmorearty** [ottypes/rich-text#20]
```
x = new Delta([{insert: "x"}]);
retain_0_delete_1 = new Delta([{retain: 0}, {delete: 1}]);
result = x.compose(retain_0_delete_1);
```

The result is `[{insert: "x"}, {delete: 1}]`. It should be just `[]`, right?

`{ retain: 0 }` can happen with programmatically generated deltas.

**Comment by jhchen** [comment]
A property of Deltas is it needs to be in the most compact form which means a Delta with { retain: 0 } is invalid. If the return of some Delta function is giving you { retain: 0 }, then please submit that as a bug.

Note constructing a new Delta with your own ops array does not go through validity checks so `new Delta([{ retain: 0 }])` is not immediately flagged as an error. This is all in the [Delta docs](https://github.com/ottypes/rich-text#deltas-1) and a good way to avoid dealing with these nuances yourself is just to chain the [`insert()`](https://github.com/ottypes/rich-text#insert), [`delete()`](https://github.com/ottypes/rich-text#delete), [`retain()`](https://github.com/ottypes/rich-text#retain) methods.
