### ISSUE TITLE
Get rid of package.json import in type.js

### ISSUE THREAD

**Issue by ksokhan** [ottypes/rich-text#22]
https://github.com/ottypes/rich-text/blob/master/lib/type.js#L2

There is no need for importing `package.json` anymore. It was used for pulling version number here: https://github.com/ottypes/rich-text/commit/7d2c20b4f08e26e239e63567678f9866965ad002 but that line has since been hardcoded.

Ran into a webpack issue where in order to use this package, I had to add .json type in webpack.

**Comment by jhchen** [comment]
You are correct. Would you like to submit a PR so you get contribution credit?
