### ISSUE TITLE
How to get a standalone browser client js?

### ISSUE THREAD

**Issue by lslzl3000** [ottypes/rich-text#24]
I need to work this without require dependencies
How to export a standalone client js version?

**Comment by jhchen** [comment]
It is on npm: https://www.npmjs.com/package/rich-text

**Comment by lslzl3000** [comment]
I do install by npm, but I see no dist/standalone js in the package.

**Comment by jhchen** [comment]
My mistake--I mistook this project for another one I have. There is no browser build. You need to use webpack, browserify or something for use on the browser client.
