### ISSUE TITLE
Presence

### ISSUE THREAD

**Issue by curran** [ottypes/rich-text#29]
Would an implementation of [presence](https://github.com/ottypes/docs/pull/27/files) be welcome in this repo?

Here are two implementations that already exist in forks:

 * https://github.com/houshuang/rich-text/pull/1/files
 * https://github.com/ottypes/rich-text/compare/master...dantedallag:master

**Comment by jhchen** [comment]
One looks like a WIP and the other unclear on its state. This seems like in the idea stage so more info would be helpful, such as pros/cons of this approach versus others, use in real life productions systems, etc.

Personally I have never implemented presence in this layer in production and am open to being enlightened but again hard to evaluate with this level of detail.

**Comment by curran** [comment]
@jhchen Thank you for your response.

For more context on the presence topic in general, see https://github.com/ottypes/docs/issues/29 . In summary, this approach is being used in production at Teamwork, but the work has progressed only in the Teamwork forks (of ShareDB and related repositories), and the presence they are using is implemented in a completely new OT type for rich text - https://github.com/Teamwork/ot-rich-text .

It's true that presence for `rich-text` is WIP, spearheaded in https://github.com/houshuang/rich-text/pull/1

**Comment by jhchen** [comment]
If this gets more progress and traction from the other ottypes folks I'll take another look.
