### ISSUE TITLE
Python port of the rich-text

### ISSUE THREAD

**Issue by zosiakropka** [ottypes/rich-text#6]
I hope it's a right place to ask such a questions. I've [starter porting](https://github.com/zosiakropka/rich-text-py) `rich-text` library to Python 2.7 and it's already quite usable (although with no test coverage yet). Now I'm not sure whether you'd find it fine if I published it under MIT licence. I'd also want to know, what kind of credits would you like me to provide for you and whether `rich-text-py` is a fair name for my repo and package. May I publish it to [PyPI](https://pypi.python.org/) once it's polished enough?

**Comment by sachinrekhi** [comment]
**zosiakropka** - I was planning on doing a Python port of the rich-text ottype myself when I came across this post. Did you end up publishing your port? Could I get a copy either way? Thanks!

**Comment by zosiakropka** [comment]
@sachinrekhi, thank you for asking. [There is such a port](https://github.com/zosiakropka/rich-text-py), but it's definitely not final and not maintained for a year. Also, the package isn't published, but one can always install easily from GitHub. If you want to use it, feel free, but I can't guarantee 100% reliability. Still, you can use it as a starting point for your own implementation and contribute. Anyway, I'll be happy to come back to this project in next few days, if you want to benefit from it.

**Comment by sachinrekhi** [comment]
@zosiakropka awesome thanks! I'lll check it out and see what I might be able to use for my own implementation!

**Comment by sachinrekhi** [comment]
FYI @zosiakropka @jhchen @josephg I finished my full port of rich-text to Python and published it on GitHub and Pypi. I ported most of Jason's tests as well to make sure it had the exact same behavior.

Feel free to use or share with others who might ask about a Python version. It's available here: https://github.com/sachinrekhi/richtextpy

**Comment by jhchen** [comment]
Awesome thanks @sachinrekhi !
