### ISSUE TITLE
Operation transformation apply deltas to server side

### ISSUE THREAD

**Issue by deepsyx** [ottypes/rich-text#9]
I'm using Quill.js together with socket.io/nodejs on backend. Quill has events for deltas, so I can send the deltas to all clients and create Collaborative editor.

I'm using https://github.com/ottypes/rich-text plugin for backend and my question is how I can apply deltas to backend document.
I can do this in Quill by doing editor.updateContents(deltas_array) and current content will be updated with the incoming deltas.

I've searched through whole rich-text plugin documentation, but I couldn't find a feature to apply deltas to a document.

**Comment by jhchen** [comment]
You'll also need something that can resolve conflicts between client changes. The best choice is probably [ShareJS](http://sharejs.org/).

**Comment by mib32** [comment]
@jhchen Jason, could you please elaborate something on that?
I thought deltas already resolved conflicts. Like i have to deltas, one inserts something and one deletes. `editor.updateContents(deltas)` handles that very good. Could you expose just some function that does the same for a string variable, like `new_string = delta.applyTo(old_string)`?

**Comment by mib32** [comment]
@jhchen 
`Note that only name, create, apply and transform are strictly required, though most types should also include url and compose.`
from https://github.com/ottypes/docs

**Comment by jhchen** [comment]
Deltas have the functions necessary for conflict resolution such as `compose` and `transform`. However something else, like ShareJS, still needs to determine when to use those functions. This repository is for rich-text only. If you want to operate on just strings, take a look at its [plaintext](https://github.com/ottypes/text) equivalent.

**Comment by mib32** [comment]
@jhchen Thanks! Though i can't and don't want to use shareJS because it lacks rich text support and i already implemented everything myself. I aggregate deltas from multiple users in some redis list, and want to sync it eventually to database, and i thought that it would be really easy to convert deltas to patch old content. I'll take a look on quill's and sharejs's functions and try to replicate them according to my targets.

**Comment by jhchen** [comment]
> Though i can't and don't want to use shareJS because it lacks rich text support

That's the whole point of this repository...
